### ISSUE TITLE
6_BWA_Gene_Map.py

### ISSUE THREAD

**Issue by kaiwang12** [ParkinsonLab/Metatranscriptome-Workshop#8]
Hi,
I got an error when running ./6_BWA_Gene_Map.py. 
Here is the error information:
Traceback (most recent call last):
  File "./6_BWA_Gene_Map.py", line 117, in <module>
    gene_map(BWA_sam_file, unmapped_reads)
  File "./6_BWA_Gene_Map.py", line 54, in gene_map
    db_match = line_parts[1]
IndexError: list index out of range

Any idea why this occurred? 
Thanks.

**Comment by NOngeso** [comment]
When running the pipeline from from top,  two files n(**mouse1_contigs_unmapped.fasta**  & **mouse1_unassembled_unmapped.fasta**) needed by 6_BWA_Gene_Map.py have not from above executions.

**Comment by NOngeso** [comment]
Was this error rectified for this step. Can we get the original script you used to execute this step
